### ISSUE TITLE
Statistics.cor could be accept a AbstractDataFrame.

### ISSUE THREAD

**Issue by robsonsilvadasilva** [JuliaLang/Statistics.jl#33]
I came from python and pandas world, and a really useful method in pandas is corr(). It accepts a DataFrame and returns the correlation between the numerical columns. 

I've tried to do that in Julia Statistics but I've got the folow error:

**MethodError: no method matching cor(::DataFrame)**

What do you think about improve cor() to accept a :DataFrame? It will remove String columns, calculate the Pearson Correlations betweeen then and return it on a DataFrame.

I am aplying here to improve this functionality if you think to be useful. 

Thank you very much,

All the best for you,

Take Care.

Robson

**Comment by ararslan** [comment]
Hello, Robson. One issue here is that the Statistics module is in Julia's standard library, which is installed by default alongside Julia. Standard library modules cannot depend on external packages. In this case, that means that Statistics can't depend on DataFrames, since DataFrames is not in the standard library. `cor` could be extended in another package, e.g. in DataFrames, though I'm not sure what the best package for that would be.

**Comment by nalimilan** [comment]
Yes, that method would have to live in DataFrames.jl. That said, I'm not sure we would add exactly that function, but there have been discussions to add `pairwise` so that you would do `pairwise(cor, df)` or `pairwise(cor, eachcol(df))`. You can file an issue in DataFrames if you want to discuss that.
